
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_DEBUG=1
    restart: always

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=http://litellm:8105
      # See ec2-setup\user-data.sh for how LITELLM_API_KEY is created
      - OPENAI_API_KEY=$LITELLM_API_KEY
      - GLOBAL_LOG_LEVEL="DEBUG"     
      - OLLAMA_BASE_URL=http://ollama:11434 
      - ENV=dev
    ports:
      - "8101:8080"
    restart: always

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    volumes:
      - ./litellm-config.yml:/app/config.yaml
    ports:
      - "8105:8105"
    environment:
      # See ec2-setup\user-data.sh for how LITELLM_API_KEY is created
      - LITELLM_API_KEY=$LITELLM_API_KEY
      - AWS_REGION=us-east-1
      - PORT=8105
    command: --config /app/config.yaml --detailed_debug

volumes:
  ollama:
  open-webui:

