model_list:
  - model_name: Nova Pro by Amazon
    litellm_params:
      model: amazon.nova-pro-v1:0
  - model_name: Claude 3.5 Sonnet by Anthropic
    litellm_params:
      model: anthropic.claude-3-5-sonnet-20240620-v1:0
  - model_name: Llama 3 8B Instruct by Meta
    litellm_params:
      model: meta.llama3-8b-instruct-v1:0
  - model_name: Mistral 7B Instruct by Mistral AI
    litellm_params:
      model: mistral.mistral-7b-instruct-v0:2

litellm_settings:
  modify_params: True
  drop_params: true
