---
- name: Setup and deploy Flask application
  hosts: localhost
  become: yes
  vars:
    app_name: "server-tool"
    port: 8108
    app_folder: "/home/ec2-user/web-apps/{{ app_name }}"

  tasks:
    - name: Install Python packages from requirements.txt
      become_user: ec2-user
      pip:
        requirements: "{{ app_folder }}/requirements.txt"

    - name: Create systemd service for Flask app
      copy:
        dest: /etc/systemd/system/{{ app_name }}.service
        content: |
          [Unit]
          Description=Flask App {{ app_name }}
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory={{ app_folder }}
          ExecStart=/bin/bash -c 'source /home/ec2-user/.bashrc && flask run --port {{ port }}'
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd to apply new service
      command: systemctl daemon-reload

    - name: Enable and start the Flask app service
      service:
        name: "{{ app_name }}"
        enabled: yes
        state: started

    - name: Copy Caddyfile
      copy:
        src: "{{ app_folder }}/{{ app_name }}.Caddyfile"
        dest: /etc/caddy/apps/{{ app_name }}.Caddyfile

    - name: Reload Caddy service
      service:
        name: caddy
        state: reloaded